
cloud:
  aws:
    region:
      static: us-east-1

loyalty:
  consumer:
    name: consumer-client-library
    kinesis:
      url: http://localhost:4567
      connection-timeout: 5000
      retries: 0
      streams:
        mystream: channelA

    dynamodb:
      url: http://localhost:3457
      connection-timeout: 2000
      retries: 0
