spring:
  cloud:
    stream:
      bindings:
        eventOut:
          destination: test-stream
          content-type: application/json
          producer:
            partitionKeyExpression: "1"
            headerMode: none


loyalty:
  messaging:
    url: http://localhost:4567
    connection-timeout: 5000
    retries: 1
    streams:
      test-stream: channelA