cloud:
  aws:
    region:
      static: us-east-1

loyalty:
  consumer:
    name: ${spring.application.name}
    kinesis:
      url: http://localhost:4567
      #url: kinesis.us-east-1.amazonaws.com
      connection-timeout: 5000
      retries: 1
      streams:
        lab-csi: channelA

    dynamodb:
      url: http://localhost:3457/
      #url: dynamodb.us-east-1.amazonaws.com
      connection-timeout: 2000
      retries: 2